Resources:

  # A CloudWatch log group to store records of events from the event bus.
  LogGroupEventBridge:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/events/${self:service}-${self:custom.stage}-event-bridge

  # A resource policy to allow EventBridge to write to the log group. The
  # CloudFormation spec unfortunately requires a JSON string for the policy
  # document, hence the mess below.
  LogGroupEventBridgeResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: ${self:service}-${self:custom.stage}-event-bridge-resource-policy
      PolicyDocument: "{ \"Version\": \"2012-10-17\", \"Statement\": [ { \"Effect\": \"Allow\", \"Principal\": { \"Service\": [ \"events.amazonaws.com\", \"delivery.logs.amazonaws.com\"  ] }, \"Action\": [ \"logs:CreateLogStream\", \"logs:PutLogEvents\"  ], \"Resource\": \"*\" } ] }"
