Resources:

  # A rule to forward all events published to the default event bus to a
  # CloudWatch log group.
  EventBridgeCloudWatchRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Forwards all events to CloudWatch for debugging"
      EventPattern:
        account:
          - !Ref AWS::AccountId
      Name: ${self:service}-${self:custom.stage}-event-bus-cloudwatch-rule
      Targets:
        - Arn: !GetAtt LogGroupEventBridge.Arn
          Id: ${self:service}-${self:custom.stage}-event-bus-cloudwatch-rule-target
